version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    groups:
      core:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: ./docs
    schedule:
      interval: daily
      time: "06:00"
      timezone: Asia/Kolkata
    commit-message:
      prefix: "chore(docs)"
    labels:
      - dependencies
      - documentation
    groups:
      docs:
        patterns: ["*"]
