version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies"
    allow:
      - dependency-type: production
    groups:
      core:
        dependency-type: production
      dev:
        dependency-type: development

  - package-ecosystem: npm
    directory: ./docs
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Asia/Kolkata
    commit-message:
      prefix: "chore(deps-docs)"
    labels:
      - dependencies
      - documentation
    groups:
      docs:
        patterns: ["*"]
