name: Create Pre-Release

on:
  push:
    tags:
      - "v*.*.*-alpha"

jobs:
  run-eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 25
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install the Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

  run-prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 25
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install the Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm format:check

  create-release:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - run-eslint
      - run-prettier
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Create  Upload Release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAG: "${{ github.ref_name }}"
        run: |
          gh release create "$TAG" \
          --title "$TAG" \
          --generate-notes \
          --prerelease \
          --verify-tag
