name: Run Test Suite

on: [push]

jobs:
  test-suite:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 25
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install the Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest
        run: pnpm test
